### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [solidninja/peroxide-cryptsetup#9]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

Looks like this is partly blocked by https://github.com/docopt/docopt.rs/issues/128. I will follow up in this issue when they have a new release ready.

**Comment by vladimir-lu** [comment]
Will have a look at this this week, thanks!
